### ISSUE TITLE
Add docs about reproducible builds

### ISSUE THREAD

**Issue by Cardosaum** [risc0/risc0#1658]
## Overview

Users should understand what's the concept of a reproducible build, why is it important, how do we achieve reproducibility etc. 

## Tasks to be done

- [ ] Write a new page on the [dev docs](https://dev.risczero.com/api) about reproducible builds
  - [ ] Should be under "Writing your zkVM application" section (the in depth explanations about the zkVM)
- [ ] Explain what is the a reproducible build
- [ ] Explain why is the reproducibility of the guest code important
- [ ] Explain how we achieve reproducibility (mention we need docker for it, `cargo` is not deterministic by default etc)
- [ ] Explain how users can build their ELFs in a reproducible way (mention `cargo risczero build`, `cargo risczero deploy` and also `risc0_build` if they want to build elfs from rust code)

**Comment by pdg744** [comment]
transferring this from dev rel board to platform board

**Comment by pdg744** [comment]
I think it's probably best to hold off on adding a dedicated page for this until we do some engineering re: #2075 -- until then, we don't have a good story for how foundry template users can access determinstic builds. 

In the mean time, we have the terminology entry: https://dev.risczero.com/terminology#deterministic-builds

The revisions to the terminology entry in #2074 improve the terminology entry to reflect the what/why/how items in the checklist above.

**Comment by pdg744** [comment]
Closing because this issue is redundant with #1084.
