### ISSUE TITLE
Solidity/Toy Verifier

### ISSUE THREAD

**Issue by cf** [risc0/risc0#270]
Are they any plans to implement a solidity verifier?

I think this would significantly boost adoption of risc0 as a plug and play layer 2. 

If there is not currently a solidity verifier in the roadmap, our team would be happy to work on/contribute a Solidity implementation if there was more documentation of the zkSTARK protocol used or a toy reference implementation to work off of.

See also #222

**Comment by juan0xmon** [comment]
Hi, I am currently working on a solidity verifier. I would be happy to collaborate

**Comment by jbruestle** [comment]
We are not currently working on a Solidity verifier ourselves due to resource constraints, but would *love* for there to be one.  In terms of documentation, we have a some of high level stuff on our website, as well as a python implementation of a ZK-Stark for a toy problem and also a minimal stand alone rust implementation of a verifier, which are currently not in the public repo (and also may be slightly out of date).  I'm attaching them here, caveat emptor.
[didactic_stark.zip](https://github.com/risc0/risc0/files/9538867/didactic_stark.zip)
[risc0-verify.tar.gz](https://github.com/risc0/risc0/files/9538869/risc0-verify.tar.gz)

**Comment by cf** [comment]
> We are not currently working on a Solidity verifier ourselves due to resource constraints, but would _love_ for there to be one. In terms of documentation, we have a some of high level stuff on our website, as well as a python implementation of a ZK-Stark for a toy problem and also a minimal stand alone rust implementation of a verifier, which are currently not in the public repo (and also may be slightly out of date). I'm attaching them here, caveat emptor. [didactic_stark.zip](https://github.com/risc0/risc0/files/9538867/didactic_stark.zip) [risc0-verify.tar.gz](https://github.com/risc0/risc0/files/9538869/risc0-verify.tar.gz)

Thanks for the reply, Jeremy. It seems that the structure of the seal u32 array has changed since the stand alone verifier was made (Verifying the seal fails at https://github.com/cf/risc0-export-verify-seal/blob/main/risc0-verify/src/verify.rs#L112, see https://github.com/cf/risc0-export-verify-seal/blob/main/starter/src/main.rs#L31). Do you by any chance know roughly when this was made or which git commit produces valid seals, I would be happy to update the code to work with 0.11.0, but it would be very helpful if you could see the git diff to better understand how the structure of the seal data has changed.

**Comment by cf** [comment]
I put together some diagrams that show a little bit more about what would be nice to accomplish with a standalone verifier, and we got the go ahead to invest some of our team's time into building this out for the risc0 community, and since this is more of a feature request than an issue, we'll publish a separate library over at https://github.com/OpenAssetStandards/dr-grouper if anyone wants to check out our progress or make a PR.


## Phase 1 Architecture
<div>
<img src="https://raw.githubusercontent.com/OpenAssetStandards/dr-grouper/main/proposal/assets/Risc0CommunityAggregatorPhase1.png" alt="Dr. Grouper Phase 1 Architecture Diagram" width="94%">
</div>

### Phase 1 Key Milestones
- [ ] Dependency-free STARK verifier library for risc0 execution receipts (written in rust)
    - [ ] Serialize/Deserialize Helpers for Receipts generated by risc0
    - [ ] Basic demo that generates a risc0 proof from a guest and serializing/saves the receipt to a receipt.bin file
    - [ ] A separate dependency-free demo which can open, parse and verify a receipt.bin file using the dependency free library
    - [ ] Create an example risc0 guest demo which shows in-guest recursive proof verification.
- [ ] Create a demo [AntelopeIO](https://github.com/AntelopeIO) smart contract using the [eosio-rust](https://github.com/sagan-software/eosio-rust) sdk which can verify a risc0 proof using the dependency-free rust verifier library



## Phase 2 Architecture
<div>
<img src="https://raw.githubusercontent.com/OpenAssetStandards/dr-grouper/main/proposal/assets/Risc0CommunityAggregatorPhase2.png" alt="Dr. Grouper Phase 2 Architecture Diagram" width="94%">
</div>


### Phase 2 Key Milestones

- [ ] Create a zkSNARK circuit capable of verifying a risc0 seal STARK proof (this could also potentially be broken up into phases of verification so that the proof can be generated in paralell and to minimize per proof gate count, since we only need to verify a single STARK proof. It is ok to need to verify 4-5 proofs on chain as verification cost for groth16 snarks is very low)
- [ ] Create an ethereum smart contract capable of verifying the zkSNARK circuit and updating/storing the 3 merkle tree root hashes (tree of elf hashes, tree of journal hashes, tree of seal hashes)
- [ ] Create an example 3rd party contract which demonstrates how to use a merkle proof to prove that the result of some execution with input arguments (x,y,z) is (a,b,c) using the tree of journal hashes and a Poseidon merkle proof
- [ ] Create a proof of concept peer to peer networking example and incentive model for decentralized proving of arbitrary risc0 executions
- [ ] Create a circom gadget which makes it easy to show how users can easily create proofs of complex relationships based on the verified inputs/outputs of multiple risc0 executions in the 3 trees and verify this fact on chain with 300k or less gas

**Comment by jbruestle** [comment]
So I think this is a very interesting project.  The phase one part largely looks like it is about getting recursion working with RISC Zero (i.e. running the verifier from within the prover).  Currently that is our most important near term goal, and almost half of our engineering staff is working on it in some way.  You are certainly welcome to contribute, but we should coordinate.  Regarding doing the STARK -> SNARK transform (i.e. verifying STARKS via SNARKS), we would love to have support for that, but currently don't have anyone working on it, so that may be a more useful place to contribute in the near term.

**Comment by flaub** [comment]
We will be announcing https://dev.risczero.com/bonsai soon which provides the ability to generate a groth16 proof which can be verified in solidity. See this example: https://github.com/risc0/risc0/tree/main/bonsai/examples/governance
